# Generated by Django 4.2.6 on 2026-10-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='observable_cells',
            field=models.CharField(blank=True, help_text='Comma-separated cell names. Leave blank to embed the whole notebook.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='observable_height',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='observable_url',
            field=models.URLField(blank=True, help_text='e.g. https://observablehq.com/@477/domestic-destinations', null=True),
        ),
    ]
